# Generated by Django 5.0.7 on 2026-09-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('college_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private'), ('DEEMED', 'Deemed University')], default='GOVERNMENT', max_length=20)),
                ('categories', models.CharField(help_text='Comma separated GoalCategory codes offered at this college', max_length=250)),
                ('rating', models.FloatField(default=4.0, help_text='Out of 5')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ENGINEERING', 'Engineering & Technology'), ('MEDICAL', 'Medicine & Healthcare'), ('DATA_SCIENCE', 'Data Science & AI'), ('COMMERCE', 'Commerce & Finance'), ('ARTS_DESIGN', 'Arts & Design'), ('LAW', 'Law'), ('GOVERNMENT', 'Government / Civil Services'), ('AGRICULTURE', 'Agriculture & Life Sciences'), ('TEACHING', 'Teaching & Education')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎯', help_text='Emoji used as a lightweight icon', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('eligible_standards', models.CharField(help_text='Comma separated StandardLevel codes this scholarship applies to', max_length=120)),
                ('eligible_categories', models.CharField(blank=True, help_text='Comma separated GoalCategory codes; blank = open to all fields', max_length=200)),
                ('amount', models.CharField(blank=True, help_text="e.g. 'Up to ₹50,000/year'", max_length=120)),
                ('official_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('CLASS_8', 'Class 8'), ('CLASS_10', 'Class 10'), ('CLASS_12', 'Class 12'), ('UNDERGRAD', 'Undergraduate'), ('POSTGRAD', 'Postgraduate / Working Professional')], max_length=16)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, help_text="e.g. '6-12 months'", max_length=80)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='core.goal')),
            ],
            options={
                'ordering': ['goal', 'standard', 'order'],
            },
        ),
    ]
